import test from 'node:test';
import assert from 'node:assert/strict';
import '../src/data.js';import '../src/tools.js';import '../src/lesson.js';
test('holdings accept the boundary and reject exceeding the limit',()=>{const d=LabData.snapshot();assert.equal(LabTools.holdings(d.order).allowed,true);d.order.quantity=3;assert.equal(LabTools.holdings(d.order).allowed,false);});
test('warehouses are ordered by driving time and include collection in SLA checks',()=>{const r=LabTools.warehouses(LabData.snapshot());assert.deepEqual(r.map(x=>x.id),['near','far']);assert.equal(r[0].enough,false);assert.equal(r[1].totalMinutes,80);assert.equal(r[1].spareMinutes,-20);assert.ok(r.every(x=>!x.eligible));});
test('peer allocation and reserve are protected, with handover time included',()=>{const d=LabData.snapshot(),r=LabTools.peer(d);assert.equal(r.available,2);assert.equal(r.totalMinutes,25);assert.equal(r.spareMinutes,35);assert.equal(r.unallocatedRemaining,2);assert.equal(r.eligible,true);d.peer.allocated=2;assert.equal(LabTools.peer(d).eligible,false);d.peer.allocated=1;d.order.windowMinutes=24;assert.equal(LabTools.peer(d).eligible,false);});
test('twelve-step lesson reveals data only after each requested tool executes',()=>{const l=new LabLesson.Lesson();for(let i=0;i<12;i++){const e=l.next();assert.equal(e.index,i);assert.equal(!!e.request,[2,5,8].includes(i));if(i<2)assert.equal(l.results.check_holdings,undefined);if(i<5)assert.equal(l.results.check_warehouses,undefined);if(i<8)assert.equal(l.results.check_nearby_technician,undefined);}assert.equal(l.done,true);assert.equal(l.next(),null);assert.match(l.events[11].evidence,/Awaiting approval/);assert.deepEqual(l.data,LabData.snapshot(),'recommendation does not transfer or reserve stock');});
test('recommendation is blocked when holdings or peer eligibility fail',()=>{for(const fail of [l=>l.data.order.maxHolding=2,l=>l.data.peer.held=3]){const l=new LabLesson.Lesson();fail(l);while(!l.done)l.next();assert.match(l.events.at(-1).evidence,/EXCEPTION/);}});
test('restart resets observations and sample data is isolated',()=>{const l=new LabLesson.Lesson();l.data.peer.held=0;assert.equal(new LabLesson.Lesson().data.peer.held,5);assert.deepEqual(new LabLesson.Lesson().results,{});});
