(() => {
  'use strict';
  const purposes={
    inspect_inputs:'The job instructions explicitly say to inspect the inputs first. The agent needs the column names and counts before it can request matching.',
    reconcile_inventory:'The previous result describes the two spreadsheets. The instructions say to use the matching function next. Ordinary code can perform exact matching and arithmetic reliably.',
    get_exception:'Read one unresolved row to identify what is missing before choosing a search.',
    search_references:'Exact matching has failed for this row. Searching its reference or description can reveal supporting records, but a similar description is not proof of the correct cost centre.',
    record_review:'The search result provides evidence to report. Keep a useful note and any candidates for a person to check; a suggestion cannot approve an allocation.',
    get_report:'All exception reviews are finished. Check input cost = allocated cost + unresolved cost, then summarise the job.'
  };
  function explain(event) {
    if(event.stage==='GOAL') return {title:'A reconciliation job arrives',who:'JOB → APPLICATION',what:'A consumption spreadsheet needs its inventory costs assigned to cost centres using a reference register.',how:'The two fictional spreadsheets are already included in this page. In a real system, receiving the files could trigger the job automatically. No one needs to ask the agent a chat question.',why:'The job has a clear outcome and rules: allocate unique exact references, investigate anything else, and retain every cost.',next:'Next: see the instructions and tool menu the application would give the LLM.'};
    if(event.stage==='ASK') return {title:'What would the LLM receive?',who:'APPLICATION → LLM · SIMULATED',what:`The example request contains the job, explicit instructions, available tools and ${event.observations} previous result(s).`,how:'In a real agent, the application sends this context to the LLM. The model uses its learned language abilities to generate a tool request. This tutorial uses scripted choices to show that exchange.',why:event.observations?'The returned results supply the next clue. An exception’s description gives the model words to search; the tool menu tells it which function can search the register.':'It does not magically know your process. We explicitly tell it to inspect the spreadsheets first, then match references, investigate exceptions and produce a report.',next:'Next: reveal one simulated LLM response. Expand the example request below to see its input.'};
    if(event.stage==='DECIDE') {
      let how='The simulated response names one tool and its arguments. In a real agent this structured response is generated by the LLM from the instructions and previous results.';
      if(event.data.tool==='search_references') how=`The previous matching result identified ${event.data.args.row_id} as an exception. This example uses “${event.data.args.query}” from the row’s reference or description as the search query. That is how the next question is formed.`;
      if(event.data.tool==='record_review') how=`The previous search returned evidence for ${event.data.args.row_id}. This response turns that result into a review note and candidate row numbers; it does not change the matching rules.`;
      return {title:'The simulated LLM chooses an action',who:'SIMULATED LLM → APPLICATION',what:event.summary,how,why:event.data.type==='answer'?'The computed report now provides the totals and outstanding exceptions needed for a grounded summary.':purposes[event.data.tool],next:event.data.type==='answer'?'Next: show the job summary.':`Next: inspect the request to ${event.data.tool}. Nothing has executed yet.`};
    }
    if(event.stage==='TOOL') return {title:'A request is not an execution',who:'REQUEST → APPLICATION',what:`The response requests ${event.data.name} with the arguments shown below.`,how:'The application checks that the function is allowed. On the next click, browser code runs it against the example data. The LLM itself does not open a spreadsheet or change a record.',why:purposes[event.data.name],next:'Next: run the function and inspect what it returns.'};
    if(event.stage==='OBSERVE') {
      const d=event.data.data;let what;
      if(!event.data.ok)what=`The function rejected the request: ${event.data.error}. That error becomes evidence for the next choice.`;
      else if(event.tool==='inspect_inputs')what=`The inputs contain ${d.consumption_rows} consumption rows and ${d.reference_rows} register rows. The result also gives their columns and explains that inventory_cost is already a line total.`;
      else if(event.tool==='reconcile_inventory')what=`Code allocated ${d.allocated_rows} rows (${d.allocated_cost}) and flagged ${d.exception_rows} exceptions (${d.unresolved_cost}). The control difference is ${d.difference}.`;
      else if(event.tool==='search_references')what=d.length?`The search found ${d.length} candidate register row(s). They are possible supporting records, not approved allocations.`:'The search found no supporting reference. That absence must be recorded, not filled with an invented cost centre.';
      else if(event.tool==='record_review')what=`A review note was recorded for ${d.row_id}. The row remains an exception. No allocation or control total changed.`;
      else if(event.tool==='get_report')what=`The report accounts for ${d.input_cost}: ${d.allocated_cost} allocated and ${d.unresolved_cost} unresolved. ${d.exception_rows} rows still need human review.`;
      else what='The function returned the original consumption row and its exception details.';
      return {title:'The application returns evidence',who:'APPLICATION → NEXT LLM INPUT',what,how:'These results are calculated from the example data. They are added to the next request so the agent can choose what to do next. This is new context, not model retraining.',why:purposes[event.tool],next:'Next: see the updated input, then the next simulated choice.'};
    }
    return {title:'Finished processing does not mean every row matched',who:'JOB SUMMARY + REVIEW QUEUE',what:'The job finishes with exact allocations and an explicit list of outstanding exceptions.',how:'The matching code maintains the totals. The simulated LLM adds review notes and candidates. In a real process, a person would correct the source reference or register, then rerun the job.',why:'Automation can complete its work while still identifying decisions a person must make. Unresolved costs stay visible and are never silently dropped.',next:'Review the table below. Restart to repeat the walkthrough, or download the example report.'};
  }
  globalThis.LabTutorial={explain};
})();
